# Generated by Django 4.1.4 on 2022-12-11 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('many_to_one', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='reportter',
            new_name='reporter',
        ),
    ]
